---
title: "Final Model"
author: "Michaela Müller"
date: "24 Januar 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(ggplot2)
library(cowplot)
```

## Bootstrapping Results
### Epochs
```{r}
epoch_train_acc <- fread("../ffnn/validation/epoch_train_acc.tsv")
epoch_train_loss <- fread("../ffnn/validation/epoch_train_losses.tsv")
epoch_val_acc <- fread("../ffnn/validation/epoch_val_acc.tsv")
epoch_val_loss <- fread("../ffnn/validation/epoch_val_losses.tsv")

epochs <- ncol(epoch_train_acc)
epoch_dt <- data.table(Epoch = rep(1:epochs, 2),
                       Accuracy = c(colMeans(epoch_train_acc), colMeans(epoch_val_acc)),
                       Loss = c(colMeans(epoch_train_loss), colMeans(epoch_val_loss)),
                       data_set = rep(c("train", "validation"), each = epochs))
epoch_dt

ggplot(epoch_dt, aes(Epoch, Accuracy, col = data_set)) +
  geom_line() +
  scale_color_brewer(palette = "Set1") +
  theme(legend.title = element_blank())

ggplot(epoch_dt, aes(Epoch, Loss, col = data_set)) +
  geom_line() +
  scale_color_brewer(palette = "Set1") +
  theme(legend.title = element_blank())
```

### Test Statistics
```{r}
test_stats <- fread("../ffnn/validation/test_stats.tsv", col.names = c("stat_name", "mean", "stderr", "confidence"))
test_stats

ggplot(test_stats, aes(stat_name, mean, fill = stat_name)) +
  geom_bar(stat = 'identity') + ylim(0, 1) +
  geom_errorbar(aes(ymin=mean-stderr, ymax=mean+stderr), width=.2) +
  geom_text(aes(label=paste(round(mean, 2), "+/-", round(stderr, 5))), vjust=-0.8, size=3.5) +
  scale_fill_brewer(palette = "Set1")
```

